-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
--  Add this to your init.lua or create a file like lua/config/filetype.lua
-- vim.filetype.add({
--   extension = {
--     k = "kcl",
--     kcl = "kcl",
--   },
--   pattern = {
--     [".*%.k"] = "kcl",
--     [".*%.kcl"] = "kcl",
--   },
-- })
